# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bundle_pb2 as bundle__pb2
import searcher_pb2 as searcher__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in searcher_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SearcherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeBundleResults = channel.unary_stream(
                '/searcher.SearcherService/SubscribeBundleResults',
                request_serializer=searcher__pb2.SubscribeBundleResultsRequest.SerializeToString,
                response_deserializer=bundle__pb2.BundleResult.FromString,
                _registered_method=True)
        self.SendBundle = channel.unary_unary(
                '/searcher.SearcherService/SendBundle',
                request_serializer=searcher__pb2.SendBundleRequest.SerializeToString,
                response_deserializer=searcher__pb2.SendBundleResponse.FromString,
                _registered_method=True)
        self.GetNextScheduledLeader = channel.unary_unary(
                '/searcher.SearcherService/GetNextScheduledLeader',
                request_serializer=searcher__pb2.NextScheduledLeaderRequest.SerializeToString,
                response_deserializer=searcher__pb2.NextScheduledLeaderResponse.FromString,
                _registered_method=True)
        self.GetConnectedLeaders = channel.unary_unary(
                '/searcher.SearcherService/GetConnectedLeaders',
                request_serializer=searcher__pb2.ConnectedLeadersRequest.SerializeToString,
                response_deserializer=searcher__pb2.ConnectedLeadersResponse.FromString,
                _registered_method=True)
        self.GetConnectedLeadersRegioned = channel.unary_unary(
                '/searcher.SearcherService/GetConnectedLeadersRegioned',
                request_serializer=searcher__pb2.ConnectedLeadersRegionedRequest.SerializeToString,
                response_deserializer=searcher__pb2.ConnectedLeadersRegionedResponse.FromString,
                _registered_method=True)
        self.GetTipAccounts = channel.unary_unary(
                '/searcher.SearcherService/GetTipAccounts',
                request_serializer=searcher__pb2.GetTipAccountsRequest.SerializeToString,
                response_deserializer=searcher__pb2.GetTipAccountsResponse.FromString,
                _registered_method=True)
        self.GetRegions = channel.unary_unary(
                '/searcher.SearcherService/GetRegions',
                request_serializer=searcher__pb2.GetRegionsRequest.SerializeToString,
                response_deserializer=searcher__pb2.GetRegionsResponse.FromString,
                _registered_method=True)


class SearcherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeBundleResults(self, request, context):
        """Searchers can invoke this endpoint to subscribe to their respective bundle results.
        A success result would indicate the bundle won its state auction and was submitted to the validator.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBundle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextScheduledLeader(self, request, context):
        """Returns the next scheduled leader connected to the block engine.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectedLeaders(self, request, context):
        """Returns leader slots for connected jito validators during the current epoch. Only returns data for this region.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectedLeadersRegioned(self, request, context):
        """Returns leader slots for connected jito validators during the current epoch.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTipAccounts(self, request, context):
        """Returns the tip accounts searchers shall transfer funds to for the leader to claim.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegions(self, request, context):
        """Returns region the client is directly connected to, along with all available regions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeBundleResults': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeBundleResults,
                    request_deserializer=searcher__pb2.SubscribeBundleResultsRequest.FromString,
                    response_serializer=bundle__pb2.BundleResult.SerializeToString,
            ),
            'SendBundle': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBundle,
                    request_deserializer=searcher__pb2.SendBundleRequest.FromString,
                    response_serializer=searcher__pb2.SendBundleResponse.SerializeToString,
            ),
            'GetNextScheduledLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextScheduledLeader,
                    request_deserializer=searcher__pb2.NextScheduledLeaderRequest.FromString,
                    response_serializer=searcher__pb2.NextScheduledLeaderResponse.SerializeToString,
            ),
            'GetConnectedLeaders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectedLeaders,
                    request_deserializer=searcher__pb2.ConnectedLeadersRequest.FromString,
                    response_serializer=searcher__pb2.ConnectedLeadersResponse.SerializeToString,
            ),
            'GetConnectedLeadersRegioned': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectedLeadersRegioned,
                    request_deserializer=searcher__pb2.ConnectedLeadersRegionedRequest.FromString,
                    response_serializer=searcher__pb2.ConnectedLeadersRegionedResponse.SerializeToString,
            ),
            'GetTipAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTipAccounts,
                    request_deserializer=searcher__pb2.GetTipAccountsRequest.FromString,
                    response_serializer=searcher__pb2.GetTipAccountsResponse.SerializeToString,
            ),
            'GetRegions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegions,
                    request_deserializer=searcher__pb2.GetRegionsRequest.FromString,
                    response_serializer=searcher__pb2.GetRegionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'searcher.SearcherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('searcher.SearcherService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SearcherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeBundleResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/searcher.SearcherService/SubscribeBundleResults',
            searcher__pb2.SubscribeBundleResultsRequest.SerializeToString,
            bundle__pb2.BundleResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/searcher.SearcherService/SendBundle',
            searcher__pb2.SendBundleRequest.SerializeToString,
            searcher__pb2.SendBundleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextScheduledLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/searcher.SearcherService/GetNextScheduledLeader',
            searcher__pb2.NextScheduledLeaderRequest.SerializeToString,
            searcher__pb2.NextScheduledLeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectedLeaders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/searcher.SearcherService/GetConnectedLeaders',
            searcher__pb2.ConnectedLeadersRequest.SerializeToString,
            searcher__pb2.ConnectedLeadersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectedLeadersRegioned(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/searcher.SearcherService/GetConnectedLeadersRegioned',
            searcher__pb2.ConnectedLeadersRegionedRequest.SerializeToString,
            searcher__pb2.ConnectedLeadersRegionedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTipAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/searcher.SearcherService/GetTipAccounts',
            searcher__pb2.GetTipAccountsRequest.SerializeToString,
            searcher__pb2.GetTipAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRegions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/searcher.SearcherService/GetRegions',
            searcher__pb2.GetRegionsRequest.SerializeToString,
            searcher__pb2.GetRegionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
